version: 2.1 # use CircleCI 2.1
orbs:
   ruby: circleci/ruby@1.1.0
   node: circleci/node@5.0.0 # Needed for javascript runtime
  #  heroku: circleci/heroku@1.0.1 # Use the Heroku orb in your config
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
      docker:
        - image: cimg/ruby:2.7.4-node
          auth:
              username: mydockerhub-user
              password: $DOCKERHUB_PASSWORD
      steps:
        - checkout # pull down our git code.
        - ruby/install-deps # use the ruby orb to install dependencies
        # - node/install-packages:
        #     cache-key: yarn.lock
        #     pkg-manager: yarn
  test:
    docker:
      - image: cimg/ruby:2.7.4-node
        auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
      - image: cimg/postgres:14.4
        auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
            POSTGRES_USER: server
            POSTGRES_DB: server_test
            POSTGRES_PASSWORD: ""
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    environment:
        BUNDLE_JOBS: "3"
        BUNDLE_RETRY: "3"
        PGHOST: 127.0.0.1
        PGUSER: server
        PGPASSWORD: ""
        RAILS_ENV: test
        
    steps:
        - checkout
        - ruby/install-deps
        # - node/install-packages:
        #     cache-key: yarn.lock
        #     pkg-manager: yarn
        - run:
            name: Wait for DB
            command: dockerize -wait tcp://localhost:5432 -timeout 1m
        - run:
            name: Database setup
            command: bundle exec rails db:schema:load --trace
        # Run rspec in parallel
        - ruby/rspec-test


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build